# Generated by Django 5.0.1 on 2024-04-15 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=80)),
                ('cell', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=800)),
                ('about', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers')),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=50)),
                ('currency', models.CharField(max_length=55)),
                ('payment_method', models.CharField(max_length=55)),
                ('donor_name', models.CharField(default='Anonymous', max_length=55)),
                ('donor_email', models.EmailField(max_length=254, null=True)),
                ('donor_cell', models.CharField(max_length=55, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.beneficiary')),
            ],
        ),
    ]
